<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Company>damysteryman</Company>
    <Copyright>Copyright © 2020 damysteryman</Copyright>
    <Description>Library .dll for handling Xenoblade Chronicles: Definive Edition save files.</Description>
    <AssemblyVersion>0.2.0.7</AssemblyVersion>
    <FileVersion>0.2.0.7</FileVersion>
    <Version>0.2.0.7</Version>
  </PropertyGroup>
</Project>